/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface InstantPayrollContract
  extends Truffle.Contract<InstantPayrollInstance> {
  "new"(meta?: Truffle.TransactionDetails): Promise<InstantPayrollInstance>;
}

export interface PaymentClaimed {
  name: "PaymentClaimed";
  args: {
    streamId: BN;
    worker: string;
    amountFLR: BN;
    amountUSD: BN;
    flrUsdPrice: BN;
    bonusTriggered: boolean;
    commitCount: BN;
    0: BN;
    1: string;
    2: BN;
    3: BN;
    4: BN;
    5: boolean;
    6: BN;
  };
}

export interface StreamCreated {
  name: "StreamCreated";
  args: {
    streamId: BN;
    employer: string;
    worker: string;
    usdRatePerInterval: BN;
    claimInterval: BN;
    totalDeposit: BN;
    0: BN;
    1: string;
    2: string;
    3: BN;
    4: BN;
    5: BN;
  };
}

export interface StreamEnded {
  name: "StreamEnded";
  args: {
    streamId: BN;
    totalClaimed: BN;
    refunded: BN;
    0: BN;
    1: BN;
    2: BN;
  };
}

type AllEvents = PaymentClaimed | StreamCreated | StreamEnded;

export interface InstantPayrollInstance extends Truffle.ContractInstance {
  BONUS_DIVISOR(txDetails?: Truffle.TransactionDetails): Promise<BN>;

  BONUS_MULTIPLIER(txDetails?: Truffle.TransactionDetails): Promise<BN>;

  FLR_USD_FEED_ID(txDetails?: Truffle.TransactionDetails): Promise<string>;

  checkBonusStatus(
    txDetails?: Truffle.TransactionDetails
  ): Promise<{ 0: BN; 1: boolean; 2: boolean }>;

  claim: {
    (
      _streamId: number | BN | string,
      _proof: {
        merkleProof: string[];
        data: {
          attestationType: string;
          sourceId: string;
          votingRound: number | BN | string;
          lowestUsedTimestamp: number | BN | string;
          requestBody: {
            url: string;
            httpMethod: string;
            headers: string;
            queryParams: string;
            body: string;
            postProcessJq: string;
            abiSignature: string;
          };
          responseBody: { abiEncodedData: string };
        };
      },
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      _streamId: number | BN | string,
      _proof: {
        merkleProof: string[];
        data: {
          attestationType: string;
          sourceId: string;
          votingRound: number | BN | string;
          lowestUsedTimestamp: number | BN | string;
          requestBody: {
            url: string;
            httpMethod: string;
            headers: string;
            queryParams: string;
            body: string;
            postProcessJq: string;
            abiSignature: string;
          };
          responseBody: { abiEncodedData: string };
        };
      },
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      _streamId: number | BN | string,
      _proof: {
        merkleProof: string[];
        data: {
          attestationType: string;
          sourceId: string;
          votingRound: number | BN | string;
          lowestUsedTimestamp: number | BN | string;
          requestBody: {
            url: string;
            httpMethod: string;
            headers: string;
            queryParams: string;
            body: string;
            postProcessJq: string;
            abiSignature: string;
          };
          responseBody: { abiEncodedData: string };
        };
      },
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _streamId: number | BN | string,
      _proof: {
        merkleProof: string[];
        data: {
          attestationType: string;
          sourceId: string;
          votingRound: number | BN | string;
          lowestUsedTimestamp: number | BN | string;
          requestBody: {
            url: string;
            httpMethod: string;
            headers: string;
            queryParams: string;
            body: string;
            postProcessJq: string;
            abiSignature: string;
          };
          responseBody: { abiEncodedData: string };
        };
      },
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  createStream: {
    (
      _worker: string,
      _usdRatePerInterval: number | BN | string,
      _claimInterval: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      _worker: string,
      _usdRatePerInterval: number | BN | string,
      _claimInterval: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<BN>;
    sendTransaction(
      _worker: string,
      _usdRatePerInterval: number | BN | string,
      _claimInterval: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _worker: string,
      _usdRatePerInterval: number | BN | string,
      _claimInterval: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  endStream: {
    (
      _streamId: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      _streamId: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      _streamId: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _streamId: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  getCurrentPrice(
    txDetails?: Truffle.TransactionDetails
  ): Promise<{ 0: BN; 1: BN; 2: BN }>;

  getStream(
    _streamId: number | BN | string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<{
    employer: string;
    worker: string;
    usdRatePerInterval: BN;
    claimInterval: BN;
    totalDeposit: BN;
    totalClaimed: BN;
    lastClaimTime: BN;
    createdAt: BN;
    active: boolean;
  }>;

  nextStreamId(txDetails?: Truffle.TransactionDetails): Promise<BN>;

  streams(
    arg0: number | BN | string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<{
    0: string;
    1: string;
    2: BN;
    3: BN;
    4: BN;
    5: BN;
    6: BN;
    7: BN;
    8: boolean;
  }>;

  methods: {
    BONUS_DIVISOR(txDetails?: Truffle.TransactionDetails): Promise<BN>;

    BONUS_MULTIPLIER(txDetails?: Truffle.TransactionDetails): Promise<BN>;

    FLR_USD_FEED_ID(txDetails?: Truffle.TransactionDetails): Promise<string>;

    checkBonusStatus(
      txDetails?: Truffle.TransactionDetails
    ): Promise<{ 0: BN; 1: boolean; 2: boolean }>;

    claim: {
      (
        _streamId: number | BN | string,
        _proof: {
          merkleProof: string[];
          data: {
            attestationType: string;
            sourceId: string;
            votingRound: number | BN | string;
            lowestUsedTimestamp: number | BN | string;
            requestBody: {
              url: string;
              httpMethod: string;
              headers: string;
              queryParams: string;
              body: string;
              postProcessJq: string;
              abiSignature: string;
            };
            responseBody: { abiEncodedData: string };
          };
        },
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        _streamId: number | BN | string,
        _proof: {
          merkleProof: string[];
          data: {
            attestationType: string;
            sourceId: string;
            votingRound: number | BN | string;
            lowestUsedTimestamp: number | BN | string;
            requestBody: {
              url: string;
              httpMethod: string;
              headers: string;
              queryParams: string;
              body: string;
              postProcessJq: string;
              abiSignature: string;
            };
            responseBody: { abiEncodedData: string };
          };
        },
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        _streamId: number | BN | string,
        _proof: {
          merkleProof: string[];
          data: {
            attestationType: string;
            sourceId: string;
            votingRound: number | BN | string;
            lowestUsedTimestamp: number | BN | string;
            requestBody: {
              url: string;
              httpMethod: string;
              headers: string;
              queryParams: string;
              body: string;
              postProcessJq: string;
              abiSignature: string;
            };
            responseBody: { abiEncodedData: string };
          };
        },
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _streamId: number | BN | string,
        _proof: {
          merkleProof: string[];
          data: {
            attestationType: string;
            sourceId: string;
            votingRound: number | BN | string;
            lowestUsedTimestamp: number | BN | string;
            requestBody: {
              url: string;
              httpMethod: string;
              headers: string;
              queryParams: string;
              body: string;
              postProcessJq: string;
              abiSignature: string;
            };
            responseBody: { abiEncodedData: string };
          };
        },
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    createStream: {
      (
        _worker: string,
        _usdRatePerInterval: number | BN | string,
        _claimInterval: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        _worker: string,
        _usdRatePerInterval: number | BN | string,
        _claimInterval: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<BN>;
      sendTransaction(
        _worker: string,
        _usdRatePerInterval: number | BN | string,
        _claimInterval: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _worker: string,
        _usdRatePerInterval: number | BN | string,
        _claimInterval: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    endStream: {
      (
        _streamId: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        _streamId: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        _streamId: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _streamId: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    getCurrentPrice(
      txDetails?: Truffle.TransactionDetails
    ): Promise<{ 0: BN; 1: BN; 2: BN }>;

    getStream(
      _streamId: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<{
      employer: string;
      worker: string;
      usdRatePerInterval: BN;
      claimInterval: BN;
      totalDeposit: BN;
      totalClaimed: BN;
      lastClaimTime: BN;
      createdAt: BN;
      active: boolean;
    }>;

    nextStreamId(txDetails?: Truffle.TransactionDetails): Promise<BN>;

    streams(
      arg0: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<{
      0: string;
      1: string;
      2: BN;
      3: BN;
      4: BN;
      5: BN;
      6: BN;
      7: BN;
      8: boolean;
    }>;
  };

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
