/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface InstantPayrollPayoutContract
  extends Truffle.Contract<InstantPayrollPayoutInstance> {
  "new"(
    _relayer: string,
    meta?: Truffle.TransactionDetails
  ): Promise<InstantPayrollPayoutInstance>;
}

export interface PayoutRecorded {
  name: "PayoutRecorded";
  args: {
    worker: string;
    flareStreamId: BN;
    amountFLR: BN;
    amountUSD: BN;
    bonusTriggered: boolean;
    commitCount: BN;
    0: string;
    1: BN;
    2: BN;
    3: BN;
    4: boolean;
    5: BN;
  };
}

type AllEvents = PayoutRecorded;

export interface InstantPayrollPayoutInstance extends Truffle.ContractInstance {
  getAllPayouts(
    _worker: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<
    {
      flareStreamId: BN;
      amountFLR: BN;
      amountUSD: BN;
      timestamp: BN;
      bonusTriggered: boolean;
      commitCount: BN;
    }[]
  >;

  getPayout(
    _worker: string,
    _index: number | BN | string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<{
    flareStreamId: BN;
    amountFLR: BN;
    amountUSD: BN;
    timestamp: BN;
    bonusTriggered: boolean;
    commitCount: BN;
  }>;

  getPayoutCount(
    _worker: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<BN>;

  recordPayout: {
    (
      _worker: string,
      _flareStreamId: number | BN | string,
      _amountFLR: number | BN | string,
      _amountUSD: number | BN | string,
      _bonusTriggered: boolean,
      _commitCount: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      _worker: string,
      _flareStreamId: number | BN | string,
      _amountFLR: number | BN | string,
      _amountUSD: number | BN | string,
      _bonusTriggered: boolean,
      _commitCount: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      _worker: string,
      _flareStreamId: number | BN | string,
      _amountFLR: number | BN | string,
      _amountUSD: number | BN | string,
      _bonusTriggered: boolean,
      _commitCount: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _worker: string,
      _flareStreamId: number | BN | string,
      _amountFLR: number | BN | string,
      _amountUSD: number | BN | string,
      _bonusTriggered: boolean,
      _commitCount: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  relayer(txDetails?: Truffle.TransactionDetails): Promise<string>;

  totalEarnedUSD(
    arg0: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<BN>;

  workerPayouts(
    arg0: string,
    arg1: number | BN | string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<{ 0: BN; 1: BN; 2: BN; 3: BN; 4: boolean; 5: BN }>;

  methods: {
    getAllPayouts(
      _worker: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<
      {
        flareStreamId: BN;
        amountFLR: BN;
        amountUSD: BN;
        timestamp: BN;
        bonusTriggered: boolean;
        commitCount: BN;
      }[]
    >;

    getPayout(
      _worker: string,
      _index: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<{
      flareStreamId: BN;
      amountFLR: BN;
      amountUSD: BN;
      timestamp: BN;
      bonusTriggered: boolean;
      commitCount: BN;
    }>;

    getPayoutCount(
      _worker: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<BN>;

    recordPayout: {
      (
        _worker: string,
        _flareStreamId: number | BN | string,
        _amountFLR: number | BN | string,
        _amountUSD: number | BN | string,
        _bonusTriggered: boolean,
        _commitCount: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        _worker: string,
        _flareStreamId: number | BN | string,
        _amountFLR: number | BN | string,
        _amountUSD: number | BN | string,
        _bonusTriggered: boolean,
        _commitCount: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        _worker: string,
        _flareStreamId: number | BN | string,
        _amountFLR: number | BN | string,
        _amountUSD: number | BN | string,
        _bonusTriggered: boolean,
        _commitCount: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _worker: string,
        _flareStreamId: number | BN | string,
        _amountFLR: number | BN | string,
        _amountUSD: number | BN | string,
        _bonusTriggered: boolean,
        _commitCount: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    relayer(txDetails?: Truffle.TransactionDetails): Promise<string>;

    totalEarnedUSD(
      arg0: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<BN>;

    workerPayouts(
      arg0: string,
      arg1: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<{ 0: BN; 1: BN; 2: BN; 3: BN; 4: boolean; 5: BN }>;
  };

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
