/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface PlasmaPayrollContract
  extends Truffle.Contract<PlasmaPayrollInstance> {
  "new"(
    _usdc: string,
    meta?: Truffle.TransactionDetails
  ): Promise<PlasmaPayrollInstance>;
}

export interface PaymentClaimed {
  name: "PaymentClaimed";
  args: {
    streamId: BN;
    worker: string;
    amount: BN;
    intervalsCount: BN;
    0: BN;
    1: string;
    2: BN;
    3: BN;
  };
}

export interface StreamCreated {
  name: "StreamCreated";
  args: {
    streamId: BN;
    employer: string;
    worker: string;
    usdcPerInterval: BN;
    claimInterval: BN;
    totalDeposit: BN;
    0: BN;
    1: string;
    2: string;
    3: BN;
    4: BN;
    5: BN;
  };
}

export interface StreamEnded {
  name: "StreamEnded";
  args: {
    streamId: BN;
    totalClaimed: BN;
    refunded: BN;
    0: BN;
    1: BN;
    2: BN;
  };
}

type AllEvents = PaymentClaimed | StreamCreated | StreamEnded;

export interface PlasmaPayrollInstance extends Truffle.ContractInstance {
  claim: {
    (
      _streamId: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      _streamId: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      _streamId: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _streamId: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  createStream: {
    (
      _worker: string,
      _usdcPerInterval: number | BN | string,
      _claimInterval: number | BN | string,
      _totalDeposit: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      _worker: string,
      _usdcPerInterval: number | BN | string,
      _claimInterval: number | BN | string,
      _totalDeposit: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<BN>;
    sendTransaction(
      _worker: string,
      _usdcPerInterval: number | BN | string,
      _claimInterval: number | BN | string,
      _totalDeposit: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _worker: string,
      _usdcPerInterval: number | BN | string,
      _claimInterval: number | BN | string,
      _totalDeposit: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  endStream: {
    (
      _streamId: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      _streamId: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      _streamId: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _streamId: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  getStream(
    _streamId: number | BN | string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<{
    employer: string;
    worker: string;
    usdcPerInterval: BN;
    claimInterval: BN;
    totalDeposit: BN;
    totalClaimed: BN;
    lastClaimTime: BN;
    createdAt: BN;
    active: boolean;
  }>;

  nextStreamId(txDetails?: Truffle.TransactionDetails): Promise<BN>;

  streams(
    arg0: number | BN | string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<{
    0: string;
    1: string;
    2: BN;
    3: BN;
    4: BN;
    5: BN;
    6: BN;
    7: BN;
    8: boolean;
  }>;

  usdc(txDetails?: Truffle.TransactionDetails): Promise<string>;

  methods: {
    claim: {
      (
        _streamId: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        _streamId: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        _streamId: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _streamId: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    createStream: {
      (
        _worker: string,
        _usdcPerInterval: number | BN | string,
        _claimInterval: number | BN | string,
        _totalDeposit: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        _worker: string,
        _usdcPerInterval: number | BN | string,
        _claimInterval: number | BN | string,
        _totalDeposit: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<BN>;
      sendTransaction(
        _worker: string,
        _usdcPerInterval: number | BN | string,
        _claimInterval: number | BN | string,
        _totalDeposit: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _worker: string,
        _usdcPerInterval: number | BN | string,
        _claimInterval: number | BN | string,
        _totalDeposit: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    endStream: {
      (
        _streamId: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        _streamId: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        _streamId: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _streamId: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    getStream(
      _streamId: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<{
      employer: string;
      worker: string;
      usdcPerInterval: BN;
      claimInterval: BN;
      totalDeposit: BN;
      totalClaimed: BN;
      lastClaimTime: BN;
      createdAt: BN;
      active: boolean;
    }>;

    nextStreamId(txDetails?: Truffle.TransactionDetails): Promise<BN>;

    streams(
      arg0: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<{
      0: string;
      1: string;
      2: BN;
      3: BN;
      4: BN;
      5: BN;
      6: BN;
      7: BN;
      8: boolean;
    }>;

    usdc(txDetails?: Truffle.TransactionDetails): Promise<string>;
  };

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
