/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface IFtsoFeedDecimalsContract
  extends Truffle.Contract<IFtsoFeedDecimalsInstance> {
  "new"(meta?: Truffle.TransactionDetails): Promise<IFtsoFeedDecimalsInstance>;
}

export interface DecimalsChanged {
  name: "DecimalsChanged";
  args: {
    feedId: string;
    decimals: BN;
    rewardEpochId: BN;
    0: string;
    1: BN;
    2: BN;
  };
}

type AllEvents = DecimalsChanged;

export interface IFtsoFeedDecimalsInstance extends Truffle.ContractInstance {
  decimalsUpdateOffset(txDetails?: Truffle.TransactionDetails): Promise<BN>;

  defaultDecimals(txDetails?: Truffle.TransactionDetails): Promise<BN>;

  getCurrentDecimals(
    _feedId: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<BN>;

  getCurrentDecimalsBulk(
    _feedIds: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<string>;

  getDecimals(
    _feedId: string,
    _rewardEpochId: number | BN | string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<BN>;

  getDecimalsBulk(
    _feedIds: string,
    _rewardEpochId: number | BN | string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<string>;

  getScheduledDecimalsChanges(
    _feedId: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<{ 0: BN[]; 1: BN[]; 2: boolean[] }>;

  methods: {
    decimalsUpdateOffset(txDetails?: Truffle.TransactionDetails): Promise<BN>;

    defaultDecimals(txDetails?: Truffle.TransactionDetails): Promise<BN>;

    getCurrentDecimals(
      _feedId: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<BN>;

    getCurrentDecimalsBulk(
      _feedIds: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;

    getDecimals(
      _feedId: string,
      _rewardEpochId: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<BN>;

    getDecimalsBulk(
      _feedIds: string,
      _rewardEpochId: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;

    getScheduledDecimalsChanges(
      _feedId: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<{ 0: BN[]; 1: BN[]; 2: boolean[] }>;
  };

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
