/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface IIncreaseManagerContract
  extends Truffle.Contract<IIncreaseManagerInstance> {
  "new"(meta?: Truffle.TransactionDetails): Promise<IIncreaseManagerInstance>;
}

type AllEvents = never;

export interface IIncreaseManagerInstance extends Truffle.ContractInstance {
  getIncentiveDuration(txDetails?: Truffle.TransactionDetails): Promise<BN>;

  methods: {
    getIncentiveDuration(txDetails?: Truffle.TransactionDetails): Promise<BN>;
  };

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
