/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface IJsonApiVerificationContract
  extends Truffle.Contract<IJsonApiVerificationInstance> {
  "new"(
    meta?: Truffle.TransactionDetails
  ): Promise<IJsonApiVerificationInstance>;
}

type AllEvents = never;

export interface IJsonApiVerificationInstance extends Truffle.ContractInstance {
  verifyJsonApi(
    _proof: {
      merkleProof: string[];
      data: {
        attestationType: string;
        sourceId: string;
        votingRound: number | BN | string;
        lowestUsedTimestamp: number | BN | string;
        requestBody: {
          url: string;
          postprocessJq: string;
          abi_signature: string;
        };
        responseBody: { abi_encoded_data: string };
      };
    },
    txDetails?: Truffle.TransactionDetails
  ): Promise<boolean>;

  methods: {
    verifyJsonApi(
      _proof: {
        merkleProof: string[];
        data: {
          attestationType: string;
          sourceId: string;
          votingRound: number | BN | string;
          lowestUsedTimestamp: number | BN | string;
          requestBody: {
            url: string;
            postprocessJq: string;
            abi_signature: string;
          };
          responseBody: { abi_encoded_data: string };
        };
      },
      txDetails?: Truffle.TransactionDetails
    ): Promise<boolean>;
  };

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
