/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface TestFtsoV2InterfaceContract
  extends Truffle.Contract<TestFtsoV2InterfaceInstance> {
  "new"(
    meta?: Truffle.TransactionDetails
  ): Promise<TestFtsoV2InterfaceInstance>;
}

export interface FeedIdChanged {
  name: "FeedIdChanged";
  args: {
    oldFeedId: string;
    newFeedId: string;
    0: string;
    1: string;
  };
}

type AllEvents = FeedIdChanged;

export interface TestFtsoV2InterfaceInstance extends Truffle.ContractInstance {
  calculateFeeById(
    _feedId: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<BN>;

  calculateFeeByIds(
    _feedIds: string[],
    txDetails?: Truffle.TransactionDetails
  ): Promise<BN>;

  getFeedById(
    _feedId: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<{ 0: BN; 1: BN; 2: BN }>;

  getFeedByIdInWei(
    _feedId: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<{ 0: BN; 1: BN }>;

  getFeedIdChanges(
    txDetails?: Truffle.TransactionDetails
  ): Promise<{ oldFeedId: string; newFeedId: string }[]>;

  getFeedsById(
    _feedIds: string[],
    txDetails?: Truffle.TransactionDetails
  ): Promise<{ 0: BN[]; 1: BN[]; 2: BN }>;

  getFeedsByIdInWei(
    _feedIds: string[],
    txDetails?: Truffle.TransactionDetails
  ): Promise<{ 0: BN[]; 1: BN }>;

  getFtsoProtocolId(txDetails?: Truffle.TransactionDetails): Promise<BN>;

  getSupportedFeedIds(
    txDetails?: Truffle.TransactionDetails
  ): Promise<string[]>;

  verifyFeedData(
    _feedData: {
      proof: string[];
      body: {
        votingRoundId: number | BN | string;
        id: string;
        value: number | BN | string;
        turnoutBIPS: number | BN | string;
        decimals: number | BN | string;
      };
    },
    txDetails?: Truffle.TransactionDetails
  ): Promise<boolean>;

  methods: {
    calculateFeeById(
      _feedId: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<BN>;

    calculateFeeByIds(
      _feedIds: string[],
      txDetails?: Truffle.TransactionDetails
    ): Promise<BN>;

    getFeedById(
      _feedId: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<{ 0: BN; 1: BN; 2: BN }>;

    getFeedByIdInWei(
      _feedId: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<{ 0: BN; 1: BN }>;

    getFeedIdChanges(
      txDetails?: Truffle.TransactionDetails
    ): Promise<{ oldFeedId: string; newFeedId: string }[]>;

    getFeedsById(
      _feedIds: string[],
      txDetails?: Truffle.TransactionDetails
    ): Promise<{ 0: BN[]; 1: BN[]; 2: BN }>;

    getFeedsByIdInWei(
      _feedIds: string[],
      txDetails?: Truffle.TransactionDetails
    ): Promise<{ 0: BN[]; 1: BN }>;

    getFtsoProtocolId(txDetails?: Truffle.TransactionDetails): Promise<BN>;

    getSupportedFeedIds(
      txDetails?: Truffle.TransactionDetails
    ): Promise<string[]>;

    verifyFeedData(
      _feedData: {
        proof: string[];
        body: {
          votingRoundId: number | BN | string;
          id: string;
          value: number | BN | string;
          turnoutBIPS: number | BN | string;
          decimals: number | BN | string;
        };
      },
      txDetails?: Truffle.TransactionDetails
    ): Promise<boolean>;
  };

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
